In [1]:
import numpy as np

In [48]:
p=[[1,2,3], [4,5,6], [7,8,89]]
p = np.asarray(p)

In [49]:
len(p)

3

In [2]:
p = np.zeros([2,2])

In [3]:
p = [np.random.rand(2,2)]

In [4]:
p

[array([[0.02204417, 0.33412668],
        [0.23035965, 0.07093374]])]

In [5]:
p.append(np.random.rand(2,2))

In [13]:
p[0][0]

array([0.02204417, 0.33412668])

In [11]:
p[1][0]

array([0.79905912, 0.47174911])

In [15]:
p.append(np.random.rand(2,1))

In [16]:
p

[array([[0.02204417, 0.33412668],
        [0.23035965, 0.07093374]]), array([[0.79905912, 0.47174911],
        [0.89554818, 0.25176025]]), array([[0.65390863],
        [0.03667659]])]

In [17]:
p[2]

array([[0.65390863],
       [0.03667659]])

In [15]:
def f():
    print("Kalyan")
    
class ComplexNumber:
    def __init__(self,r = 0,i = 0, k=0):
        self.real = r
        self.imag = i
        self.k = k

    def getData(self, a =0):
        
        print("{0}+{1}j+{2}k".format(self.real,self.imag, self.k))
        print(f())


# Create a new ComplexNumber object
c1 = ComplexNumber(2,3,7)

# Call getData() function
# Output: 2+3j
c1.getData(2)

# Create another ComplexNumber object
# and create a new attribute 'attr'
c2 = ComplexNumber(5)
c2.attr = 10

# Output: (5, 0, 10)
print((c2.real, c2.imag, c2.attr))

# # but c1 object doesn't have attribute 'attr'
# # AttributeError: 'ComplexNumber' object has no attribute 'attr'
# c1.attr

2+3j+7k
Kalyan
None
(5, 0, 10)
